name: run scraper
on: 
  schedule:
    - cron:  '0 13 * * *'
    # schedule action to run every day at 1:00 PM UTC (9:00 AM ET)
    # * is a special character in yml, so this string needs to be enclosed in quotes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content # checkout the repository content
        uses: actions/checkout@v4.1.1 

      - name: Setup Python # install python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11.8' # use version needed

      - name: install python packages # install packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install requests
          pip install gspread
          pip install oauth2client
          pip install gspread_dataframe

      - name: execute py script # run python script
        env:
            AUTH_CREDENTIALS: ${{ secrets.AUTH_CREDENTIALS }}
        run: python cal-oes-scraper/cal-oes-scraper.py

      - name: commit files # commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated spreadsheet" --allow-empty)

      - name: GitHub Push #push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

